# Generated by Django 3.2 on 2023-01-24 10:57

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo',
            field=models.FileField(blank=True, default='customers/nopp.jpg', null=True, upload_to=master.models.property_image_upload_to),
        ),
    ]
