# Generated by Django 3.2 on 2023-01-29 07:53

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_property_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50)),
                ('name_lc', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_no', models.CharField(blank=True, max_length=16, null=True)),
                ('floor_no', models.CharField(blank=True, max_length=16, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=16, null=True)),
                ('room_no', models.CharField(blank=True, max_length=16, null=True)),
                ('total_area', models.CharField(blank=True, max_length=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, default='customers/nopp.jpg', null=True, upload_to=master.models.sub_property_file_upload_to)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.contract')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.customer')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.property')),
            ],
            options={
                'db_table': 'third_party',
            },
        ),
    ]
